# Generated by Django 5.2.6 on 2025-09-24 10:18

import overlay_tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('overlay_file', models.ImageField(upload_to=overlay_tool.models.overlay_upload_to)),
                ('gps_nw', models.CharField(max_length=50)),
                ('gps_ne', models.CharField(max_length=50)),
                ('gps_sw', models.CharField(max_length=50)),
                ('gps_se', models.CharField(max_length=50)),
                ('qr_file', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
